const DATA={
'Ciências':{
'Matemática':{'7.ª Classe':{'Números e operações':[
['Quanto é 7 + 8?',['13','14','15','16'],2,'7 + 8 = 15.'],
['Quanto é 6 × 7?',['36','42','48','56'],1,'6 × 7 = 42.']] }},
'Física':{'7.ª Classe':{'Introdução à Física':[
['Qual grandeza mede a quantidade de matéria de um corpo?',['Força','Massa','Velocidade','Potência'],1,'A massa está relacionada com a quantidade de matéria.']] }},
'Química':{'7.ª Classe':{'Introdução à Química':[
['Qual é o objeto fundamental de estudo da Química?',['Apenas os seres vivos','A matéria, suas propriedades e transformações','Somente os astros','Apenas movimentos'],1,'A Química estuda a matéria, suas propriedades, composição, estrutura e transformações.'],
['Qual é uma propriedade da matéria?',['Massa','Democracia','Cidadania','História'],0,'A massa é uma propriedade geral da matéria.']],'Matéria e suas propriedades':[
['Qual estado possui volume definido, mas assume a forma do recipiente?',['Sólido','Líquido','Gasoso','Plasma'],1,'O líquido tem volume definido e forma variável.']]}},
'Biologia':{'7.ª Classe':{'Célula':[
['Qual é a unidade estrutural e funcional básica dos seres vivos?',['Átomo','Célula','Órgão','Ecossistema'],1,'A célula é a unidade básica dos seres vivos.']]}}},
'Conhecimentos de Angola':{
'História de Angola':{'Geral':{'História':[['Qual é a capital de Angola?',['Benguela','Huambo','Luanda','Dundo'],2,'Luanda é a capital de Angola.']]}},
'Organização política e administrativa':{'Geral':{'Estado':[['Qual documento estabelece os fundamentos e organização essencial do Estado?',['Constituição','Horário','Recibo','Mapa'],0,'A Constituição estabelece os fundamentos e a organização essencial do Estado.']]}},
'Administração Pública':{'Geral':{'Princípios':[['A Administração Pública deve atuar segundo a legalidade e o quê?',['Interesse público','Arbitrariedade','Ausência de controlo','Preferências pessoais'],0,'A atuação administrativa deve observar a legalidade e o interesse público.']]}},
'Patriotismo e cidadania':{'Geral':{'Cidadania':[['Cidadania envolve:',['Só direitos','Só deveres','Direitos e deveres','Nenhuma responsabilidade'],2,'Cidadania envolve direitos, deveres e participação responsável.']]}}},
'Educação':{
'Didática Geral':{'Universidade':{'Fundamentos':[['A Didática estuda principalmente:',['Astronomia','Ensino e aprendizagem','Meteorologia','Geologia'],1,'A Didática estuda e orienta os processos de ensino e aprendizagem.']]}},
'Metodologia de Ensino':{'Universidade':{'Métodos':[['Um método de ensino é:',['Uma forma organizada de conduzir o ensino','Uma nota','Um edifício','Um documento'],0,'Métodos são formas organizadas de conduzir o ensino e favorecer a aprendizagem.']]}},
'Pedagogia':{'Universidade':{'Fundamentos':[['A Pedagogia relaciona-se principalmente com:',['Educação e formação humana','Astronomia','Química apenas','Meteorologia'],0,'A Pedagogia estuda a educação e a formação humana.']]}},
'Avaliação da aprendizagem':{'Universidade':{'Avaliação':[['A avaliação formativa serve para:',['Acompanhar e orientar a aprendizagem','Impedir feedback','Avaliar só no fim','Eliminar correções'],0,'A avaliação formativa acompanha o processo e orienta intervenções.']]}}}
};
const icons={'Matemática':'➗','Física':'⚡','Química':'⚗️','Biologia':'🧬','História de Angola':'📜','Organização política e administrativa':'🏛️','Administração Pública':'📋','Patriotismo e cidadania':'🇦🇴','Didática Geral':'📚','Metodologia de Ensino':'👨🏾‍🏫','Pedagogia':'🎓','Avaliação da aprendizagem':'✅'};
const S={d:'',n:'',c:'',q:[],i:0,p:0,h:[],qty:0}, area=document.getElementById('quizArea');
const esc=x=>String(x??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
function show(){area.classList.remove('hide');area.scrollIntoView({behavior:'smooth'});}
function render(filter=''){let f=filter.toLowerCase(),g={};for(const [a,ds] of Object.entries(DATA))for(const d of Object.keys(ds))if((a+' '+d).toLowerCase().includes(f))(g[a]??=[]).push(d);document.getElementById('categories').innerHTML=Object.entries(g).map(([a,ds])=>`<div class="category"><h3>${esc(a)}</h3><div class="cards">${ds.map(d=>`<button class="card" data-d="${esc(d)}"><i>${icons[d]||'📘'}</i><strong>${esc(d)}</strong><small>Escolher nível e conteúdo</small></button>`).join('')}</div></div>`).join('')||'<p class="muted">Nenhuma opção encontrada.</p>';document.querySelectorAll('.card').forEach(x=>x.onclick=()=>discipline(x.dataset.d))}
function discipline(d){S.d=d;S.n='';S.c='';area.innerHTML=`<div class="box"><div class="muted">DISCIPLINA</div><h2>${esc(S.d)}</h2><p class="muted">Escolha o nível.</p><div class="grid">${['7.ª Classe','8.ª Classe','9.ª Classe','10.ª Classe','11.ª Classe','12.ª Classe','Universidade'].map(n=>`<button class="choice" data-n="${esc(n)}">🎓 <b>${esc(n)}</b><small>${DATA[S.d]?.[n]?' Conteúdos disponíveis':' Em expansão'}</small></button>`).join('')}</div><br><button class="btn secondary" id="back">← Voltar</button></div>`;document.querySelectorAll('[data-n]').forEach(x=>x.onclick=()=>level(x.dataset.n));document.getElementById('back').onclick=()=>area.classList.add('hide');show()}
function level(n){S.n=n;let d=DATA[S.d]?.[n];if(!d){area.innerHTML=`<div class="box"><h2>${esc(n)}</h2><p class="muted">Este nível ainda não tem questões locais. A estrutura está pronta para receber conteúdos.</p><button class="btn secondary" id="b">← Voltar</button></div>`;document.getElementById('b').onclick=()=>discipline(S.d);return}area.innerHTML=`<div class="box"><div class="muted">${esc(S.d)} · ${esc(S.n)}</div><h2>Escolha o conteúdo</h2><div class="content-list">${Object.entries(d).map(([c,q])=>`<button class="content" data-c="${esc(c)}">📘 <span><b>${esc(c)}</b><small>${q.length} questões base</small></span> →</button>`).join('')}</div><br><button class="btn secondary" id="b">← Voltar</button></div>`;document.querySelectorAll('[data-c]').forEach(x=>x.onclick=()=>content(x.dataset.c));document.getElementById('b').onclick=()=>discipline(S.d)}
function content(c){S.c=c;let q=DATA[S.d][S.n][c];area.innerHTML=`<div class="box"><div class="muted">CONFIGURAÇÃO</div><h2>${esc(c)}</h2><p class="muted">${esc(S.d)} · ${esc(S.n)}</p><label>Quantidade</label><select id="qty">${[5,10,15,20].filter(x=>x<=q.length).map(x=>`<option>${x}</option>`).join('')}<option value="${q.length}" selected>${q.length} questões disponíveis</option></select><button class="btn primary" id="start">🚀 Iniciar simulado</button> <button class="btn secondary" id="b">← Voltar</button></div>`;document.getElementById('start').onclick=()=>start(+document.getElementById('qty').value);document.getElementById('b').onclick=()=>level(S.n)}
function start(qty){let q=[...DATA[S.d][S.n][S.c]].sort(()=>Math.random()-.5);S.q=q.slice(0,Math.min(qty,q.length));S.qty=S.q.length;S.i=0;S.p=0;S.h=[];question()}
function question(){let q=S.q[S.i],n=S.i+1,total=S.q.length;area.innerHTML=`<div class="box"><div class="top"><div><div class="muted">${esc(S.d)}</div><h3>Questão ${n}/${total}</h3></div><b>🏆 ${S.p}</b></div><div class="progress"><div style="width:${n/total*100}%"></div></div><div class="question"><small>${esc(S.n)} · ${esc(S.c)}</small><h2>${esc(q[0])}</h2></div><div class="answers">${q[1].map((a,i)=>`<button class="answer" data-i="${i}"><b>${String.fromCharCode(65+i)})</b> ${esc(a)}</button>`).join('')}</div><div id="fb"></div></div>`;document.querySelectorAll('.answer').forEach(b=>b.onclick=()=>answer(+b.dataset.i));show()}
function answer(i){let q=S.q[S.i],bs=[...document.querySelectorAll('.answer')],ok=i===q[2];bs.forEach(b=>b.disabled=true);bs[i].classList.add(ok?'correct':'wrong');if(!ok)bs[q[2]].classList.add('correct');if(ok)S.p++;S.h.push({q:q[0],mine:q[1][i],right:q[1][q[2]],ok,e:q[3]});document.getElementById('fb').innerHTML=`<div class="feedback ${ok?'ok':'no'}"><b>${ok?'✅ Correta':'❌ Incorreta'}</b><p>${esc(ok?q[3]:'Resposta correta: '+q[1][q[2]]+' — '+q[3])}</p></div><button class="btn primary" id="next">${S.i<S.q.length-1?'Próxima questão →':'Ver resultado'}</button>`;document.getElementById('next').onclick=()=>{S.i++;S.i<S.q.length?question():result()}}
function result(){let t=S.q.length,e=t-S.p,p=Math.round(S.p/t*100);area.innerHTML=`<div class="box"><div style="text-align:center;font-size:55px">🏆</div><div class="muted" style="text-align:center">RESULTADO FINAL</div><h2 style="text-align:center">Simulado concluído</h2><div class="score">${S.p}/${t}<div style="font-size:24px">${p}%</div></div><div class="summary"><div>📊<b>${S.p}/${t}</b>Resultado</div><div>✅<b>${S.p}</b>Acertos</div><div>❌<b>${e}</b>Erros</div><div>🎯<b>${p}%</b>Aproveitamento</div></div><h3>📝 Revisão das respostas</h3><div class="review">${S.h.map((x,i)=>`<article><b>${x.ok?'✅':'❌'} Questão ${i+1}</b><p><b>Sua resposta:</b> ${esc(x.mine)}</p><p><b>Resposta correta:</b> ${esc(x.right)}</p><p><b>💡 Explicação:</b> ${esc(x.e)}</p></article>`).join('')}</div><br><button class="btn primary" id="again">🔄 Refazer</button> <button class="btn secondary" id="other">📖 Outro conteúdo</button></div>`;document.getElementById('again').onclick=()=>start(S.qty);document.getElementById('other').onclick=()=>level(S.n);show()}
function ia(t){t=t.toLowerCase();if(t.includes('fotossíntese'))return'A fotossíntese converte energia luminosa em energia química. Nas plantas, utiliza principalmente CO₂ e água e produz matéria orgânica e O₂.';if(t.includes('átomo')||t.includes('atomo'))return'O átomo é a unidade básica de um elemento químico. Possui núcleo com protões e neutrões e eletrões associados ao núcleo.';if(t.includes('reação')||t.includes('reacao'))return'Uma reação química transforma substâncias em novas substâncias por reorganização dos átomos. A conservação dos átomos é refletida no balanceamento da equação.';if(t.includes('derivada'))return'A derivada representa a taxa de variação instantânea de uma função e, geometricamente, o declive da reta tangente.';if(t.includes('didática')||t.includes('didatica'))return'A Didática estuda e orienta os processos de ensino e aprendizagem, incluindo objetivos, conteúdos, métodos, recursos e avaliação.';return'Posso ajudar a explicar conceitos, resolver exercícios e criar perguntas. Esta versão funciona localmente; uma IA generativa de nível ChatGPT precisa de uma API/backend.'}
document.getElementById('search').oninput=e=>render(e.target.value);document.getElementById('menu').onclick=()=>document.getElementById('nav').classList.toggle('open');document.getElementById('send').onclick=send;document.getElementById('iaInput').onkeydown=e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();send()}};function send(){let x=document.getElementById('iaInput'),t=x.value.trim();if(!t)return;let m=document.getElementById('messages');m.insertAdjacentHTML('beforeend',`<div class="msg user">${esc(t)}</div>`);x.value='';setTimeout(()=>m.insertAdjacentHTML('beforeend',`<div class="msg">${esc(ia(t))}</div>`),200)}render();
